#name: Building & Deploying the application
#
#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
#
#jobs:
#  maven-build:
#
#    runs-on: ubuntu-latest
#
#    services:
#      mysql:
#        image: mysql:8.2.0
#        ports:
#          - 3306:3306
#
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v4
#
#      - name: Setup JDK 21
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'corretto'
#          cache: maven
#
#      - name: Unit Tests
#        run: mvn test
#
#      - name: Build the application
#        run: |
#          mvn test
#          mvn package
#
#
#
#      - name: Build Docker Image
#        uses: docker/build-push-action@v6
#        with:
#            context: .
#            dockerfile: Dockerfile
#            push: false
#            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gradesmart:latest
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#              username: ${{ secrets.DOCKER_HUB_USERNAME }}
#              password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#
#      - name: Push to Docker Hub
#        uses:  docker/build-push-action@v6
#        with:
#              context: .
#              dockerfile: Dockerfile
#              push: true
#              tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gradesmart:latest
#
name: Building & Deploying the application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  maven-build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.2.0
        ports:
          - 3306:3306

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Unit Tests
        run: mvn test

      - name: Build the application (Package)
        run: mvn package

  docker-build:
    runs-on: ubuntu-latest
    needs: maven-build  # This ensures that this job runs after maven-build finishes

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          build-args: JAR_FILE=target/GradeSmart-0.0.1-SNAPSHOT.jar
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gradesmart:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          build-args: JAR_FILE=target/GradeSmart-0.0.1-SNAPSHOT.jar
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gradesmart:latest



