

name: Building & Deploying the application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.2.0
        ports:
          - 3306:3306

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Unit Tests
        run: mvn test

      - name: Build the application
        run: |
          mvn test
          mvn package

